// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20250409094020_FeedDb")]
    partial class FeedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Electronics",
                            Description = "Ergonomic wireless mouse with adjustable DPI and silent clicks.",
                            ImageUrl = "https://picsum.photos/id/102/300/200",
                            Name = "Wireless Mouse",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Electronics",
                            Description = "RGB backlit mechanical keyboard with blue switches.",
                            ImageUrl = "https://picsum.photos/id/104/300/200",
                            Name = "Mechanical Keyboard",
                            Price = 89.5m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Accessories",
                            Description = "1-liter stainless steel reusable water bottle.",
                            ImageUrl = "https://picsum.photos/id/1080/300/200",
                            Name = "Water Bottle",
                            Price = 15.75m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Audio",
                            Description = "Over-ear headphones with active noise cancellation and 30-hour battery life.",
                            ImageUrl = "https://picsum.photos/id/180/300/200",
                            Name = "Noise Cancelling Headphones",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Wearables",
                            Description = "Fitness-focused smartwatch with heart rate monitoring and GPS.",
                            ImageUrl = "https://picsum.photos/id/249/300/200",
                            Name = "Smartwatch",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Furniture",
                            Description = "Comfortable ergonomic gaming chair with lumbar support.",
                            ImageUrl = "https://picsum.photos/id/335/300/200",
                            Name = "Gaming Chair",
                            Price = 299m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Home Office",
                            Description = "Adjustable LED desk lamp with touch control and USB charging port.",
                            ImageUrl = "https://picsum.photos/id/151/300/200",
                            Name = "LED Desk Lamp",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Accessories",
                            Description = "Durable laptop backpack with multiple compartments and waterproof material.",
                            ImageUrl = "https://picsum.photos/id/1011/300/200",
                            Name = "Backpack",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Audio",
                            Description = "Compact wireless speaker with powerful sound and 10-hour battery life.",
                            ImageUrl = "https://picsum.photos/id/241/300/200",
                            Name = "Portable Bluetooth Speaker",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Footwear",
                            Description = "Lightweight and breathable running shoes for daily training.",
                            ImageUrl = "https://picsum.photos/id/21/300/200",
                            Name = "Running Shoes",
                            Price = 120m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
